name: "subdivx"
guid: "9f420e7a-3ae6-4073-9bc9-81da6dea8143"
imageUrl: ""
version: 1
targetAbi: "10.10.0.0"
framework: "net8.0"
owner: "lvitti"
overview: "Download subtitles for your media"
description: "Download subtitles from the internet to use with your media files. (Requires configuration)"
category: "Metadata"